apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: java-sample-b2lf
  namespace: mdsaud-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:dc9610256a9a65d6e0bc8a49173fe288ebfc49b5c51c3f5b772f71abef7a122a
        name: my-java-quarkus
        resources: {}
status: {}
