apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: java-sample-b2lf
  namespace: mdsaud-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:a5a3c8e0336b24dd386206a19c769717a5a56db62fc98d613f22d19704245806
        name: my-java-quarkus
        resources: {}
status: {}
